services:
  game-service:
    container_name: game_service_app
    image: ghcr.io/${GHCR_USERNAME_LC:-kumuditharanasinghe}/game_service:latest
    logging:
    ports:
      - "8004:8004"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/game_service?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-kumuditha}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-kumuditha1234}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8004
      TZ: "Asia/Colombo"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - default

  mysql:
    image: mysql:8.0
    container_name: game_service_mysql
    environment:
      MYSQL_DATABASE: game_service
      MYSQL_USER: ${DB_USER:-kumuditha}
      MYSQL_PASSWORD: ${DB_PASSWORD:-kumuditha1234}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-kumuditha1234}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

volumes:
  mysql_data:


networks:
  default:
    driver: bridge
