name: CICD

on:
  push:
    branches: [release/game-service]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin

      - name: Build docker image
        run: docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/game_service:latest .

      - name: Publish image to GHCR
        run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/game_service:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Create local env file
        run: |
          echo "GHCR_USERNAME_LC=$(echo '${{ secrets.GHCR_USERNAME }}' | tr '[:upper:]' '[:lower:]')" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Login and Deploy with Docker Compose
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | sudo docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
          # Remove existing containers to avoid name conflicts during transition to compose
          sudo docker rm -f game_service_app game_service_mysql || true
          sudo docker compose pull
          sudo docker compose up -d --force-recreate

